import "./globals.css";
import { League_Spartan } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";

const leagueSpartan = League_Spartan({ subsets: ["latin"] });

export const metadata = {
  title: "Frontend Mentor | Room homepage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={leagueSpartan.className}>
        <Header />
        <div className="container">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
